create table if not exists public.horarios (
  id bigint generated by default as identity primary key,
  dia text not null,
  periodo integer not null check (periodo between 1 and 9),
  horario text not null,
  sala text not null,
  turma text not null,
  materia text not null
);

create table if not exists public.provas (
  id bigint generated by default as identity primary key,
  data date not null,
  horario text not null,
  sala text not null,
  turma text not null,
  materia text not null
);

alter table public.horarios enable row level security;
alter table public.provas enable row level security;

create policy "Karen pode consultar horarios"
  on public.horarios for select
  using (true);

create policy "Karen pode consultar provas"
  on public.provas for select
  using (true);